### ISSUE TITLE
AAL atlas

### ISSUE THREAD

**Issue by jianghc93** [jrieke/cnn-interpretability#1]
Hi I am currently looking through your jupyter notebook `interpretation-mri.ipynb`.

I have 2 questions regarding the AAL atlas you use to form the masks:

1) Where did you get the names of the brain regions for the variable `area_names`?

2) You resize the atlas to match the shape of the brain images. However, resizing will not ensure the regions of the brain image matches up with the AAL atlas? Would some form of registration to the AAL atlas be necessary before forming the mask?

Thanks!

**Comment by derEitel** [comment]
Hi,
thanks for your interest in our work.

1. When you download the AAL atlas from [here](http://www.gin.cnrs.fr/en/tools/aal-aal2/) you will find a readme file with all region names. For AAL2 there is also a .txt file which contains the region names.

2. Since the brain images were registered beforehand they match the AAL atlas. While it may not be a perfect match we have manually checked the fitting on many of our images. Regarding resizing I would recommend to use the `nilearn.image.resample_img` or `nilearn.image.resample_to_img` functions.

**Comment by jianghc93** [comment]
Hi @derEitel ,

Appreciate your reply.

1) I am slightly confused about this, as your paper states that you are using a ICBM template. Is it the same as the AAL atlas?

> We downloaded T1-weighted MPRAGE scans and nonlinearly registered all images to a 1 mm isotropic ICBM template"

My images are currently registered to the MNI152_T1_2mm template. I guess in my case I would not be able to use the AAL atlas directly? 


2) In your paper you mentioned that the salient regions were calculated by "summing the relevance in each area". I am wondering if we should also consider the size of each region. For example, let's say Region A covers 100 voxels with each voxel having a weight of 0.1. Region B covers 10 voxels with each voxel having a weight of 0.5. Region A (total weight: 10) will be more important than Region B (total weight: 5) even though most of its voxels have smaller weights.

**Comment by derEitel** [comment]
1. It is not the same but as both are within MNI space they can be close enough. If you want a more precise relation between atlas and your data you should register the data to it directly. You could check whether your data fits the AAL atlas by overlaying the atlas on some images.
2. You are right, normalizing the relevance to the area size is also very interesting! We have made a comparison in a more recent paper here: https://github.com/moboehle/Pytorch-LRP

**Comment by jianghc93** [comment]
I will check the paper out.

Appreciate your clarifications!
